site_name: embedding

nav:
  - Recherches théoriques: 
      - Principes de l'embedding: index.md
      - Les différents types d'embedding: 
        - Frequency-Based Embeddings: frequency.md
        - Prediction-Based Embeddings: prediction.md
        - Contextualized Word Embeddings: contextualized.md
      - Création des embeddings: creation.md

  - Expérimentations: 
      - Premières expériences: experimentations/premieres_experiences.md
      - API & Visualisations: experimentations/api_visualisations.md
      - LLM: experimentations/llm.md

  - Application:
      - Maquettes: 
        - Inspiration: inspiration.md
        - Premières ébauches: ebauches.md
        - Maquettes: maquettes.md
      - Recherches techniques:
          - Introduction: contexte_technos.md
          - Front-end: front-end_technos.md
          - Intégration JS: integration-js_technos.md
          - Conclusion: conclusion_technos.md
          - installation: installation.md
  - Conclusions: conclusions_personnelles.md
          


theme: readthedocs