site_name: embedding

nav:
  - Recherches théoriques: 
      - Principes de l'embedding: index.md
      - Les différents types d'embedding: 
        - Frequency-Based Embeddings: frequency.md
        - Prediction-Based Embeddings: prediction.md
        - Contextualized Word Embeddings: contextualized.md
      - Création des embeddings: creation.md

  - Expérimentations: 
      - Démarches: demarches.md
      - Résultats: resultats.md
  - Application:
      - Recherches:
          - Introduction: contexte_technos.md
          - Front-end: front-end_technos.md
          - Intégration JS: integration-js_technos.md
          - Conclusion: conclusion_technos.md
      


theme: readthedocs